### ISSUE TITLE
UTF-8 MISO Error

### ISSUE THREAD

**Issue by Wolsen21** [gridstatus/gridstatus#403]
```
import gridstatus 
miso = gridstatus.MISO()
miso.get_interconnection_queue()
```

This code returns the following error, unknown if an issue with the API or MISO:

```
Traceback (most recent call last):
  File "c:\Users\User\Desktop\Code\help.py", line 3, in <module>
    miso.get_interconnection_queue()
  File "C:\Users\User\AppData\Local\anaconda3\Lib\site-packages\gridstatus\miso.py", line 304, in get_interconnection_queue
    data = json.loads(raw_data.read().decode("utf-8"))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\anaconda3\Lib\json\__init__.py", line 335, in loads
    raise JSONDecodeError("Unexpected UTF-8 BOM (decode using utf-8-sig)",
json.decoder.JSONDecodeError: Unexpected UTF-8 BOM (decode using utf-8-sig): line 1 column 1 (char 0)
```

Just appeared in the last few hours. Similar is occuring with all_queue requests.

Upon further inspection, it seems like MISO has changed their reporting format for date-time values, as I am having trouble accessing the info directly using the link. Unsure how to fix though, I will leave that up to you all.

**Comment by WillKoehrsen** [comment]
Thanks for letting us know. We are currently looking into a MISO outage so that may be related.

**Comment by Wolsen21** [comment]
https://www.misoenergy.org/planning/resource-utilization/GI_Queue/gi-interactive-queue/

Thanks for getting right on it! Does seem to be a MISO issue not Grid Status.

**Comment by WillKoehrsen** [comment]
Thanks for reporting the issue! MISO data is back up and your code snippet worked for me. If you confirm, I'll close this out.

**Comment by WillKoehrsen** [comment]
Closing as the issue was related to MISO not `gridstatus`.
