### ISSUE TITLE
Ercot Wind and Solar Actual data coming empty after name change

### ISSUE THREAD

**Issue by iamanonym0us** [gridstatus/gridstatus#445]
Ercot Wind and Solar Actual System Data coming in as empty after ERCOT name change. This is with the new code that was updated 4 days ago. Thanks.

**Comment by kmax12** [comment]
Hi - I see you closed this issue. just want to confirm the problem in case anyone else comes across it. 

One possible explanation for what you may have seen is that each report contains future time intervals. The actuals for solar and wind will be null in that future data for a given report

**Comment by iamanonym0us** [comment]
Hi - This is good. I am sorry. I forgot to refresh the kernel after replacing the code. My bad. Also, are you planning to push the update soon as whole package ? Thanks.

**Comment by WillKoehrsen** [comment]
> Also, are you planning to push the update soon as whole package?

A new release is a good idea. I will do that.
